// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/25/2025, 1:11:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Development/NextJS/fintekindonesia/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/plugins/**/*.{js,ts,mjs}","D:/Development/NextJS/fintekindonesia/composables/**/*.{js,ts,mjs}","D:/Development/NextJS/fintekindonesia/utils/**/*.{js,ts,mjs}","D:/Development/NextJS/fintekindonesia/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Development/NextJS/fintekindonesia/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;